
Formations = {
    "3-1-4-2" : ["GK", "CB", "CB", "CB", "RM", "CM", "CM", "CDM", "LM", "ST", "ST"],
    "3-4-1-2" : ["GK", "CB", "CB", "CB", "RM", "CM", "CM", "CAM", "LM", "ST", "ST"],
    "3-4-2-1" : ["GK", "CB", "CB", "CB", "RM", "CM", "CM", "LM", "CF", "CF", "ST"],
    "3-4-3" : ["GK", "CB", "CB", "CB", "RM", "CM", "CM", "LM", "RW", "LW", "ST"],
    "3-5-2" : ["GK", "CB", "CB", "CB", "RM", "CDM", "CDM", "LM", "CAM", "ST", "ST"],
    "4-1-2-1-2" : ["GK", "LB", "CB", "CB", "RB", "RM", "CDM", "LM", "CAM", "ST", "ST"],
    "4-1-2-1-2(2)" : ["GK", "LB", "CB", "CB", "RB", "RM", "CDM", "LM", "CAM", "ST", "ST"],
    "4-1-3-2" : ["GK", "LB", "CB", "CB", "RB", "RM", "CDM", "LM", "CM", "ST", "ST"],
    "4-1-4-1" : ["GK", "LB", "CB", "CB", "RB", "RM", "CDM", "CM", "CM", "LM", "ST"],
    "4-2-1-3" : ["GK", "LB", "CB", "CB", "RB", "CDM", "CM", "CDM", "RW", "LW", "ST"],
    "4-2-2-2" : ["GK", "LB", "CB", "CB", "RB", "CDM", "CDM", "CAM", "CAM", "ST", "ST"],
    "4-2-3-1" : ["GK", "LB", "CB", "CB", "RB", "CDM", "CDM", "CAM", "CAM", "CAM", "ST"],
    "4-2-3-1(2)" : ["GK", "LB", "CB", "CB", "RB", "CDM", "CDM", "CAM", "LM", "RM", "ST"],
    "4-2-4" : ["GK", "LB", "CB", "CB", "RB", "CM", "CM", "LW", "RW", "ST", "ST"],
    "4-3-1-2" : ["GK", "LB", "CB", "CB", "RB", "CM", "CM", "CM", "CAM", "ST", "ST"],
    "4-3-2-1" : ["GK", "LB", "CB", "CB", "RB", "CM", "CM", "CM", "CF", "CF", "ST"],
    "4-3-3" : ["GK", "LB", "CB", "CB", "RB", "CM", "CM", "CM", "LW", "RW", "ST"],
    "4-3-3(2)" : ["GK", "LB", "CB", "CB", "RB", "CDM", "CM", "CM", "LW", "RW", "ST"],
    "4-3-3(3)" : ["GK", "LB", "CB", "CB", "RB", "CDM", "CDM", "CM", "LW", "RW", "ST"],
    "4-3-3(4)" : ["GK", "LB", "CB", "CB", "RB", "CM", "CM", "CAM", "LW", "RW", "ST"],
    "4-3-3(5)" : ["GK", "LB", "CB", "CB", "RB", "CDM", "CM", "CM", "LW", "RW", "CF"],
    "4-4-1-1" : ["GK", "LB", "CB", "CB", "RB", "LM", "CM", "CF", "CM", "RM", "ST"],
    "4-4-1-1(2)" : ["GK", "LB", "CB", "CB", "RB", "LM", "CM", "CAM", "CM", "RM", "ST"],
    "4-4-2" : ["GK", "LB", "CB", "CB", "RB", "LM", "CM", "CM", "RM", "ST", "ST"],
    "4-4-2(2)" : ["GK", "LB", "CB", "CB", "RB", "LM", "CDM", "CDM", "RM", "ST", "ST"],
    "4-5-1" : ["GK", "LB", "CB", "CB", "RB", "LM", "CAM", "CM", "CAM", "RM", "ST"],
    "4-5-1(2)" : ["GK", "LB", "CB", "CB", "RB", "LM", "CM", "CM", "CM", "RM", "ST"],
    "5-2-1-2": ["GK", "LWB", "CB", "CB", "CB", "RWB", "CM", "CM", "CAM", "ST", "ST"],
    "5-2-2-1": ["GK", "LWB", "CB", "CB", "CB", "RWB", "CM", "CM", "LW", "RW", "ST"],
    "5-2-3": ["GK", "LWB", "CB", "CB", "CB", "RWB", "CM", "CM", "LW", "RW", "ST"],
    "5-3-2": ["GK", "LWB", "CB", "CB", "CB", "RWB", "CM", "CDM", "CM", "ST", "ST"],
    "5-4-1": ["GK", "LWB", "CB", "CB", "CB", "RWB", "LM", "CM", "CM", "RM", "ST"],
}
